port: 8080
base_url:
authorization_server_url:
api_base_url:
transport: http
log_level: debug

supported_scopes:
  - openid
  - offline_access
  - offline

response_types_supported:
  - code
  - code id_token
  - id_token
  - token id_token
  - token
  - token id_token code

grant_types_supported:
  - authorization_code
  - refresh_token

code_challenge_methods_supported:
  - S256

token_endpoint_auth_methods_supported:
  - none

issuer:
authorization_endpoint:
token_endpoint:
revoke_endpoint:
mcp_server_token:
