port: 8080
base_url: https://mac-8080.bhautik.in
authorization_server_url: https://mac-4444.bhautik.in
api_base_url: https://api-createos.nodeops.network
transport: http
log_level: debug

supported_scopes:
  - openid
  - offline_access
  - offline

response_types_supported:
  - code
  - code id_token
  - id_token
  - token id_token
  - token
  - token id_token code

grant_types_supported:
  - authorization_code
  - refresh_token

code_challenge_methods_supported:
  - S256

token_endpoint_auth_methods_supported:
  - none

issuer: https://mac-4444.bhautik.in
authorization_endpoint: https://mac-4444.bhautik.in/oauth2/auth
token_endpoint: https://mac-4444.bhautik.in/oauth2/token
revoke_endpoint: https://mac-4444.bhautik.in/oauth2/revoke
