name: image-build-push

on:
  push:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  image-build-push:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.asdf/installs/golang
            ~/.asdf/plugins/golang
            ~/.asdf/installs/golang/*/packages/pkg/mod
            ~/.cache/go-build
            ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-${{ hashFiles('**/go.sum') }}

      # - name: Run golangci-lint
      #   run: |
      #     set -x
      #     golangci-lint cache status
      #     golangci-lint run

      - name: Test
        run: |
          set -x
          go test -tags dev ./...

      - name: Build
        run: |
          set -x
          CGO_ENABLED=0	go build -trimpath -ldflags="-s -w -extldflags '-static'" -o nodeops main.go
          ldd nodeops || true

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Get tags
        id: timestamp
        run: |
          echo "timestamp=$(date +%s)" >>$GITHUB_OUTPUT
          echo "git_short_sha=$(git rev-parse --short ${{ github.sha }})" >>$GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            reg.nodeops.xyz/nodeops/autogen-backend-v2-mcp
          tags: |
            type=raw,value=${{ github.ref_name }}-${{ steps.timestamp.outputs.git_short_sha }}-${{ steps.timestamp.outputs.timestamp }}

      - name: login to container registry
        if: ${{ contains('main', github.ref_name) }}
        uses: docker/login-action@v3
        with:
          registry: reg.nodeops.xyz
          username: "robot-gha-autogen-v2-mcp"
          password: ${{ secrets.NODEOPS_REG_PASSWORD }}

      - name: Build and push
        if: ${{ contains('main', github.ref_name) }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
